services:
  backend:
    build:
      context: ./backend-directory
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      # - ./backend-directory/data:/app/data
      - ./backend-directory:/app/backend
    ports:
      - "5001:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-directory
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      # - ./backend-directory/data:/app/public/data:ro
      - ./frontend-directory:/app/frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - NEXT_PUBLIC_EXTERNAL_API_URL=http://localhost:5001
    depends_on:
      - backend
    restart: unless-stopped
